export const FETCH_QUESTION_POOL = "FETCH_QUESTION_POOL";
export const FETCH_TICKETS = "FETCH_TICKETS";
export const UPDATE_USER_ANSWER_POOL = "UPDATE_USER_ANSWER_POOL";
export const REMOVE_AN_ANSWER = "REMOVE_AN_ANSWER";
export const RESTART_QUESTIONNAIRE = "RESTART_QUESTIONNAIRE";
